### ISSUE TITLE
Runtime error for the co-existence of multiple Conda root directories

### ISSUE THREAD

**Issue by SinaMostafanejad** [molssi-seamm/seamm_installer#11]
* seamm_installer version: 2021.6.5
* Python version: 3.9
* Operating System: Linux Ubuntu 18.04 LTS

### Description

- Subject:
Runtime error when running the **seamm-installer install** command.

- Reason:
Co-existence of two conda roots; in this case, one from _intelpython/oneAPI_ and the other from _anaconda3_

- Temporary solution:
Removal of the oneAPI root directory address from **~/.conda/environment.txt** file.

### What I Did

Running 

```python
seamm-installer install
```
gives the following Traceback

```
Traceback (most recent call last):
  File "/home/sina/Packages/anaconda3/envs/seamm/bin/seamm-installer", line 10, in <module>
    sys.exit(run())
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/__main__.py", line 55, in run
    installer = seamm_installer.SEAMMInstaller(environment=environment)
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/seamm_installer.py", line 63, in __init__
    self.seamm_environment = environment
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/seamm_installer.py", line 99, in seamm_environment
    self._seamm_environment = self.conda.active_environment
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/seamm_installer.py", line 81, in conda
    self._conda = Conda()
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/conda.py", line 32, in __init__
    self._initialize()
  File "/home/sina/Packages/anaconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/conda.py", line 163, in _initialize
    raise RuntimeError(
RuntimeError: Found two roots for the Conda installation: /home/sina/Packages/intel/oneapi/intelpython/latest and /home/sina/Packages/anaconda3.

```

**Comment by seamm** [comment]
Closed by PR #13
