### ISSUE TITLE
conda search fails due to memory usage on small memory systems

### ISSUE THREAD

**Issue by paulsaxe** [molssi-seamm/seamm_installer#32]
* seamm_installer version: 2022.6.30
* Python version: 3.9
* Operating System: Linux

### Description

Installer fails with errors like this

```
seamm-installer install mopac-step
Finding all the packages that make up SEAMM. This may take several minutes.
.............WARNING:seamm_installer.conda:expected output from conda search --json --override-channels -c local -c conda-forge seamm, got
Traceback (most recent call last):
  File "/root/miniconda3/envs/seamm/lib/python3.9/site-packages/seamm_installer/conda.py", line 423, in search
    output = json.loads(stdout)
  File "/root/miniconda3/envs/seamm/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/seamm/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/envs/seamm/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
When run manually on machine with 2 GB memory, `conda search` fails with exit status of 137.

**Comment by paulsaxe** [comment]
This is not easy to fix, and machines with such small memory are rare (cloud machines maybe more common! if so pay for a slightly larger machine!!!!).

Will not fix.
