### ISSUE TITLE
seamm-installer GUI fails with Python 3.10

### ISSUE THREAD

**Issue by janash** [molssi-seamm/seamm_installer#38]
* seamm_installer version: 2022.8.22
* Python version:  3.10
* Operating System: Linux and  WSL

### Description

Opening `seamm-installer` from the command line using Python 3.10. I receive the error message:

```
seamm-installer
WARNING:pint.util:The name chemistry was already registered for another context.
Traceback (most recent call last):
  File "/home/janash/miniconda3/envs/seamm/bin/seamm-installer", line 10, in <module>
    sys.exit(run())
  File "/home/janash/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_installer/__main__.py", line 98, in run
    gui = GUI(logger=my.logger)
  File "/home/janash/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_installer/gui.py", line 132, in __init__
    self.root = self.setup()
  File "/home/janash/miniconda3/envs/seamm/lib/python3.10/site-packages/seamm_installer/gui.py", line 185, in setup
    self._gui_only = tk.IntVar(0)
  File "/home/janash/miniconda3/envs/seamm/lib/python3.10/tkinter/__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "/home/janash/miniconda3/envs/seamm/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'
```

### What I Did
I typed ``seamm-installer` into my terminal

**Comment by paulsaxe** [comment]
This appears to be an incompatible changing in tkinter.IntVar between Python 3.9 and 3.10. The fix appears to be simple: call `tk.IntVar(value=x)`.
